version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.0.0
jobs:
  build:
    docker:
      - image: circleci/python
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          command: |
            pip install -r requirements.txt
      - pulumi/preview:
          stack: dev
