name: Pipenv Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest
    
    steps:
    - uses: docker://alpine
      run: |
        stat $GITHUB_WORKSPACE
        find $GITHUB_WORKSPACE
        stat /github
        find /github
    - uses: ./.github/actions/pipenv-check
